### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by drewandersen** [allo-/virtual_webcam_background#17]
Followed the steps in the README, and when executing `python3 virtual_webcam.py`, I get the following error:
```
Traceback (most recent call last):
  File "/home/drew/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 94, in _ProcessGraphDefParam
    graph_def.MergeFrom(old_graph_def)
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.GraphDef got Graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtual_webcam.py", line 88, in <module>
    tf.graph_util.import_graph_def(graph_def, name='')
  File "/home/drew/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/drew/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/drew/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 464, in _import_graph_def_internal
    graph_def = _ProcessGraphDefParam(graph_def)
  File "/home/drew/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 96, in _ProcessGraphDefParam
    raise TypeError('graph_def must be a GraphDef proto.')
TypeError: graph_def must be a GraphDef proto.
```
I have a v4l2loopback device at `/dev/video4`, and I have the following in my config file:
```
segmentation_threshold: 0.75
blur: 15
erode: 50
dilate: 45
background_filters: []
foreground_filters: []
result_filters: []
background_image: "/home/drew/Pictures/weps1dh5ovt31.jpg"
debug_show_mask: false
virtual_video_device: "/dev/video4"
real_video_device: "/dev/video0"
average_masks: 3
```

`pip list | grep tensor` shows the following versions:
```
tensorboard           2.1.1          
tensorflow            2.1.0          
tensorflow-cpu        2.1.0          
tensorflow-estimator  2.1.0          
tensorflow-hub        0.7.0          
tensorflowjs          1.7.3       
```

I tried taking a shallow dive here, but I'm not terribly familiar with python and tensorflow. Any ideas?

**Comment by allo-** [comment]
This is probably related to tfjs-to-tf refactoring, see https://github.com/patlevin/tfjs-to-tf/issues/9.

v0.5.0 used another code, then I adapted for the master branch and now I probably need to adapt to 1.0.0.

As they now have a package on pypi, I will update the code for the released package later.

**Comment by allo-** [comment]
Can you test with the current master branch? Maybe you need to uninstall the old git-version of tfjs-graph-converter / tfjs-to-tf before installing tfjs-graph-converter==1.0.0 from pypi.

**Comment by drewandersen** [comment]
That did the trick! Thanks!
