### ISSUE TITLE
Resnet50 model causing reshape error

### ISSUE THREAD

**Issue by watsaig** [allo-/virtual_webcam_background#26]
First of all, thank you for this excellent program! I started off with the mobilenet model, which worked fine, but I wanted to try the ResNet model. 

I followed the instructions, downloading the `bodypix_resnet50_float_model-stride16` model. I changed `model_path` to point to this, and changed the preprocessing lines to this:

```
    # Preprocessing for resnet
    m = np.array([-123.15, -115.90, -103.06])
    resized_frame = np.add(resized_frame, m)

    # Preprocessing for mobilenet
    #resized_frame = np.divide(resized_frame, 127.5)
    #resized_frame = np.subtract(resized_frame, 1.0)
```

The model loads, but then I get the error:
```
Traceback (most recent call last):
  File "./virtual_webcam.py", line 254, in <module>
    mainloop()
  File "./virtual_webcam.py", line 184, in mainloop
    mask = np.reshape(mask, mask.shape[:2])
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/craig/virtualenv/virtual_webcam/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/craig/virtualenv/virtual_webcam/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/craig/virtualenv/virtual_webcam/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 9830400 into shape (480,640)
```

Did I miss something?

**Comment by allo-** [comment]
I think this got lost in the documentation / code, but the resnet model has a slightly different result tensor, so you need to change `result[1]` to `result[6]`.

See
https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/resnet.ts
https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/mobilenet.ts

**Comment by watsaig** [comment]
That's it! Thank you for your help!

**Comment by allo-** [comment]
I added a `model` configuration option. You can now choose the model like this:

```
model: "resnet50"
output_stride: 16
```

**Comment by morckx** [comment]
I'm still (or again?) getting this error:

```
raceback (most recent call last):
  File "./virtual_webcam.py", line 315, in <module>
    mainloop()
  File "./virtual_webcam.py", line 229, in mainloop
    mask = np.reshape(mask, mask.shape[:2])
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/kupietz/.local/share/virtualenvs/virtual_webcam_background-f-fm1_O9/lib64/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/kupietz/.local/share/virtualenvs/virtual_webcam_background-f-fm1_O9/lib64/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/kupietz/.local/share/virtualenvs/virtual_webcam_background-f-fm1_O9/lib64/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 5222400 into shape (480,640)
```

**Comment by allo-** [comment]
I guess that was the reason to use tensor names instead of indices.
