### ISSUE TITLE
apply_filters() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by frankenstein91** [allo-/virtual_webcam_background#35]
Unfortunately I have to report a bug with this script. I did a test under Python 3.8 and 3.7. The bug occurs in both Python versions 

python -V
Python 3.7.7
Python 3.8.3

```
Reloading config.
Model: mobilenet (multiplier=0.5, stride=16)
Loading model...
done.
Traceback (most recent call last):
  File "./virtual_webcam.py", line 308, in <module>
    mainloop()
  File "./virtual_webcam.py", line 274, in mainloop
    heatmap_masks, layer_filters)
TypeError: apply_filters() takes 4 positional arguments but 5 were given
python ./virtual_webcam.py  3,37s user 2,63s system 145% cpu 4,120 total
```

```
pip freeze
absl-py==0.9.0
astunparse==1.6.3
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
gast==0.3.3
google-auth==1.16.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.0
Keras-Preprocessing==1.1.2
Markdown==3.2.2
numpy==1.18.4
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
Pillow==7.1.2
prompt-toolkit==1.0.14
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyfakewebcam==0.1.0
Pygments==2.6.1
PyInquirer==1.0.3
PyYAML==5.3.1
regex==2020.5.14
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.4.1
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-cpu==2.2.0
tensorflow-estimator==2.2.0
tensorflow-hub==0.7.0
tensorflowjs==1.7.4.post1
termcolor==1.1.0
tfjs-graph-converter==1.0.0
urllib3==1.25.9
wcwidth==0.2.2
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
```

**Comment by allo-** [comment]
Indeed, the commit introducing the heatmap masks was incomplete.
I added this to the incomplete commit, so you need to reset two commits and then pull again.
